CREATE DATABASE Task2;
USE Task2;
CREATE TABLE job(job_name varchar(30),job_vaccince bigint,job_states int,job_capital varchar(5),job_teritoris int,job_malls bigint,job_tradition varchar(10),coutry_languages varchar(40),job_cities int,job_agriculture double);
DESC job;
CREATE TABLE sports(sports_name varchar(50),sports_no int,sports_largest_rivr varchar(70),sports_rivers_merged bigint,sports_aqualife bigint,sports_largest_aqualife varchar(40),sports_ships int,sports_water_qantity double,sports_beaaches bigint,sports_number int);
DESC sports;
CREATE TABLE cricket(cricket_name varchar(10),cricket_no int,cricket_larger_one varchar(10),content_type varchar(30),cricket_lives bigint,cricket_area bigint,cricket_width double,cricket_feaatures varchar(50),cricket_atmosphere varchar(40),cricket_countries_no int);
DESC cricket;
CREATE TABLE government(government_name varchar(30),government_type varchar(60),goverment_head varchar(32),government_sectors int,government_funds bigint,government_budjet bigint,government_employees bigint,goverment_meetings int,government_parties int,government_companies bigint);
CREATE TABLE electrcity(electrcity_type varchar(20),electrcityity_name varchar(20),electrcity_stations bigint,electrcity_properties int,electrcityian_no bigint,electrcity_station_id int,electrcityc_poles bigint,electrcity_nature varchar(10),electrcity_connection_number bigint,electrcity_switches bigint);
DESC electrcity;
ALTER TABLE job ADD COLUMN job_id int;
ALTER TABLE job ADD COLUMN job_code varchar(20);
ALTER TABLE job ADD COLUMN job_area double;
ALTER TABLE job ADD COLUMN job_currency varchar(48);
ALTER TABLE job ADD COLUMN job_region varchar(10);
ALTER TABLE job ADD COLUMN job_time_zone varchar(56);
ALTER TABLE job ADD COLUMN job_gdp int;
ALTER TABLE job ADD COLUMN job_independence_date int;
ALTER TABLE job ADD COLUMN job_president varchar(47);
ALTER TABLE job ADD COLUMN job_flag_colour varchar(72);
SELECT * FROM job;
DESC job;
ALTER TABLE job DROP COLUMN job_gdp;
ALTER TABLE job DROP COLUMN job_population;
ALTER TABLE job MODIFY COLUMN job_time_zone int;
ALTER TABLE job MODIFY COLUMN job_area float;
ALTER TABLE job MODIFY COLUMN job_code int;
ALTER TABLE job RENAME COLUMN job_agriculture TO job_farming;
ALTER TABLE job RENAME COLUMN job_code TO job_pin;
ALTER TABLE job RENAME COLUMN job_time_zone TO job_latitude;
ALTER TABLE job RENAME COLUMN job_region TO job_place;
ALTER TABLE job RENAME COLUMN job_currency TO job_economy;
ALTER TABLE sports ADD COLUMN sports_id int;
ALTER TABLE sports ADD COLUMN sports_surface_area varchar(20);
ALTER TABLE sports ADD COLUMN sports_average_depth float;
ALTER TABLE sports ADD COLUMN sports_marine_life varchar(63);
ALTER TABLE sports ADD COLUMN sports_salinity float;
ALTER TABLE sports ADD COLUMN sports_tectonic_plate varchar(84);
ALTER  TABLE sports ADD COLUMN sports_geological_features varchar(23);
ALTER TABLE sports ADD COLUMN sports_shipping_routes varchar(54);
ALTER TABLE sports ADD COLUMN sports_last_updated int;
ALTER TABLE sports ADD COLUMN sports_sourroundings_countries varchar(78);
SELECT * FROM sports;
ALTER TABLE sports DROP COLUMN sports_no;
ALTER TABLE sports DROP COLUMN sports_id;
ALTER TABLE sports MODIFY COLUMN sports_salinity int;
ALTER TABLE sports MODIFY COLUMN sports_beaches float;
ALTER TABLE sports MODIFY COLUMN sports_last_updated double;
ALTER TABLE sports RENAME COLUMN sports_geological_features TO sports_environment;
ALTER TABLE sports RENAME COLUMN sports_surrounding_countries TO sports_job_name;
ALTER TABLE sports RENAME COLUMN sports_shipping_routes TO sports_water_routes;
ALTER TABLE sports RENAME COLUMN sports_last_updated TO sports_current_updated;
ALTER TABLE sports RENAME COLUMN sports_marine_life TO sports_water_life;
DESC sports;
ALTER TABLE government ADD COLUMN government_id int;
ALTER TABLE government ADD COLUMN goverment_job_id int;
ALTER TABLE government ADD COLUMN head_of_governmnt int;
ALTER TABLE government ADD COLUMN government_capital_city varchar(54);
ALTER TABLE government ADD COLUMN government_founding_date int;
ALTER TABLE government ADD COLUMN government_construction varchar(34);
ALTER TABLE government ADD COLUMN goverment_legistative_branch varchar(76);
ALTER TABLE government ADD COLUMN government_elections varchar(84);
ALTER TABLE government ADD  COLUMN government_last_updated int;
ALTER TABLE government ADD COLUMN government_term_duration int;
SELECT * FROM government;
ALTER TABLE government DROP COLUMN goverment_head;
ALTER TABLE government DROP COLUMN government_budjet;
ALTER TABLE government MODIFY COLUMN goverment_job_id float;
ALTER TABLE government MODIFY COLUMN goverment_term_duration double;
ALTER TABLE government MODIFY COLUMN goverment_last_updated float;
ALTER TABLE government RENAME COLUMN government_job_id TO job_id;
ALTER TABLE government RENAME COLUMN government_term_duration TO trem_duration;
ALTER TABLE government RENAME COLUMN government_last_updated TO last_updated;
ALTER TABLE government RENAME COLUMN government_parties TO rural_parties;
ALTER TABLE government RENAME COLUMN government_companies TO industries;
DESC government;
ALTER TABLE electrcity ADD COLUMN electrcity_id int;
ALTER TABLE electrcity ADD COLUMN electrcity_name varchar(90);
ALTER TABLE electrcity ADD COLUMN electrcity_conductivity float;
ALTER TABLE electrcity ADD COLUMN electrcity_resistivity int;
ALTER TABLE electrcity ADD COLUMN electrcity_breakdown_voltage float;
ALTER TABLE electrcity ADD COLUMN electrcity_melting_point double;
ALTER TABLE electrcity ADD COLUMN electrcity_thermal_counductivity int;
ALTER TABLE electrcity ADD COLUMN electrcity_specific_heat float;
ALTER TABLE electrcity ADD COLUMN electrcity_chemical_formula varchar(85);
ALTER TABLE electrcity ADD COLUMN electrcity_magnetic_properties varchar(334);
SELECT * FROM electrcity;
ALTER TABLE electrcity DROP COLUMN electrcity_conductivity;
ALTER TABLE electrcity DROP COLUMN electrcity_resistivity;
ALTER TABLE electrcity MODIFY COLUMN electrcity_specific_heat int;
ALTER TABLE electrcity MODIFY COLUMN electrcity_melting_point float;
ALTER TABLE electrcity MODIFY COLUMN electrcity_id bigint;
ALTER TABLE electrcity RENAME COLUMN electrcity_properties TO electrcity_materials;
ALTER TABLE electrcity RENAME COLUMN electrcity_nature TO electrcity_ecosystem;
ALTER TABLE electrcity RENAME COLUMN electrcity_melting_point TO electrcity_melting_stage;
ALTER TABLE electrcity RENAME COLUMN electrcity_specific_heat TO electrcity_speciific_temparature;
ALTER TABLE electrcity RENAME COLUMN electrcity_switches TO electrcity_routers;
DESC electrcity;
ALTER TABLE cricket ADD COLUMN area varchar(76);
ALTER TABLE cricket ADD COLUMN lrgest_job varchar(20);
ALTER TABLE cricket ADD COLUMN capital_city varchar(70);
ALTER TABLE cricket ADD COLUMN currency varchar(43);
ALTER TABLE cricket ADD COLUMN  gdp int;
ALTER TABLE cricket ADD COLUMN highest_point varchar(50);
ALTER TABLE cricket ADD COLUMN climate varchar(83);
ALTER TABLE cricket ADD COLUMN time_zone varchar(30);
ALTER TABLE cricket ADD COLUMN current_updated int;
ALTER TABLE cricket ADD COLUMN noof_cricket int;
SELECT * FROM cricket;
ALTER TABLE cricket DROP COLUMN area;
ALTER TABLE cricket DROP COLUMN gdp;
ALTER TABLE cricket MODIFY COLUMN current_updated float;
ALTER TABLE cricket MODIFY COLUMN currency float;
ALTER TABLE cricket MODIFY COLUMN noof_cricket double;
ALTER TABLE cricket RENAME COLUMN current_updated TO past_updated;
ALTER TABLE cricket RENAME COLUMN currency TO profit;
ALTER TABLE cricket RENAME COLUMN noof_cricket TO capacity;
ALTER TABLE cricket RENAME COLUMN highest_point TO lowest_point;
ALTER TABLE cricket RENAME COLUMN climate TO weather;
DESC cricket;